
d <- c(5,6,2,3,4,2,1,5,3)
e <- c(3,2,4,5,1,2,1,3,1)
x_d = matrix(d,3,3)
x_e = matrix(e,3,3)

invObj <- makeCacheMatrix(x_d)
invObj$get()
invObj$getinv()
cacheSolve(invObj)
invObj$getinv()
cacheSolve(invObj)
invObj$set(x_d)
cacheSolve(invObj)
invObj$set(x_e)
cacheSolve(invObj)
invObj$getinv()
cacheSolve(invObj)
invObj$set(x_e)
cacheSolve(invObj)